### ISSUE TITLE
Do Folger need to sign off on the user stories?

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/shakespeares_world#1]
@VVH I was talking to @camallen about this just now, and he suggested we get Folger to sign off on the user stories as well as doing it internally. 

I remember you saying that they're keen to be involved, and it would help pin down the scope of the project - do you think they'd want to do that?

**Comment by rogerhutchings** [comment]
Also, first

**Comment by VVH** [comment]
I suspect it would help us to determine the extent to which we were building for experts and to what extent for non-experts. I think we need to focus on non-experts but this should be discussed in detail with our Folger partners.
