### ISSUE TITLE
Sizes of genre circles / spacing in the demo

### ISSUE THREAD

**Issue by pding001** [zooniverse/shakespeares_world#123]
For some reason, the display of the circles/ovals for the genres appears differently with some browsers. I'm using Chrome.  See attached picture. The "Diplomatic Papers" genre circle is larger and more egg-shaped than the others. This doesn't seem to happen when I view the demo page in FireFox. The circles seem large in general for either browser, actually – could the circles be a touch smaller? (Also, there's a fair amount of screen-space real estate between them and the "Get Started" area, too. Will that space separating the areas be reduced?)
 
![genre-circles](https://cloud.githubusercontent.com/assets/14045319/10914153/1d4c8510-821f-11e5-91b2-eff4e54790f5.JPG)

**Comment by simoneduca** [comment]
@pding001 thanks will take a look at it.
