### ISSUE TITLE
Application confuses consecutive use of "Identify Graphic" tool for "pan image" move command.

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/shakespeares_world#139]
Expected Behaviour:
* While "Identify Graphic" tool is selected, all click-drag behaviour should create graphic markers (i.e. highlighted overlays)
* This overwrites the usual click-drag behaviour, which causes the view on the subject image to pan.

Actual Behaviour:
* The first graphic marker is created correctly by a click-drag input.
* However, once the user closes the "Select One Graphic Type" menu (either by clicking X or Save Changes), then the second, third, etc click-drag input will try to SIMULTANEOUSLY create a graphic marker while panning the image.
* This behaviour is reset if the "Identify Graphic" tool is deselected, and reselected again. The first graphic marker works correctly again, but the second, third, etc all experience the same errors.

Related Issue: Application allows for multiple graphic markers to be placed without completing the first one.

Test Details:
* Win 10/Chrome 46/Not logged into Zooniverse - ERROR CONFIRMED
* Win 10/Firefox 41/Not logged into Zooniverse - ERROR CONFIRMED
* Mac OSX Yosemite/Chrome 46/Not logged into Zooniverse - ERROR CONFIRMED
* Mac OSX Yosemite/Firefox 42/Not logged into Zooniverse - ERROR CONFIRMED

**Comment by simoneduca** [comment]
Closed via 3ca36cfa95d2c40491c50fc57c0dbef19c6b3b00 (Not yet merged)
