### ISSUE TITLE
Application allows for multiple graphic markers to be placed without completing the first one.

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/shakespeares_world#140]
Expected Behaviour:
* Once a user selects the "Identify Graphic" tool, a click-drag input will create a graphic marker.
* Once the graphic marker is created, a "Select One Graphic Type" dialogue box should pop up.
* The user is expected to choose one option before clicking "Save Changes" before he/she can proceed to mark other graphics.

Actual Behaviour:
* The user is able to continuously draw new graphic markers without closing the "Select One Graphic Type" dialogue box.

Notes:
* Actually closing the dialogue box will lead to another issue. (See: Application confuses consecutive use of "Identify Graphic" tool for "pan image" move command.)
* (UNKNOWN STATUS - EXPECTED BEHAVIOUR?) If a user opts to close the "Select One Graphic Type" dialogue box, the corresponding graphic marker isn't removed. The marker appears to stay on the screen, with no actual data associated with it, although it can be further edited/deleted.

Related Issue: Application confuses consecutive use of "Identify Graphic" tool for "pan image" move command.

Test Details:
* Win 10/Chrome 46/Not logged into Zooniverse - ERROR CONFIRMED
* Win 10/Firefox 41/Not logged into Zooniverse - ERROR CONFIRMED
* Mac OSX Yosemite/Chrome 46/Not logged into Zooniverse - ERROR CONFIRMED
* Mac OSX Yosemite/Firefox 42/Not logged into Zooniverse - ERROR CONFIRMED

**Comment by simoneduca** [comment]
Closed via 3ca36cfa95d2c40491c50fc57c0dbef19c6b3b00
