### ISSUE TITLE
"Transcribe Text" tool marker moves like a yo-yo in Firefox

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/shakespeares_world#141]
Expected Behaviour:
* When a user selects a "Transcribe Text" tool, the first click should create a "pulsating red ball" overlay marker.

Actual Behaviour:
* Instead of simply pulsating, the red ball oscillates to an upper-left position and back, creating a yo-yo effect.

Hypothesis:
* This is specific to Firefox.
* There is an issue with the x-y offset during the animation/transformation.
* This possibly applies to the "Edit/Delete" popup menu as well - instead of the menu popping up near where the user clicks a text or graphic marker, the menu pops up at the upper left corner of the app viewscreen.

Test Details:
* Win 10/Chrome 46/Not logged into Zooniverse - No error
* Win 10/Firefox 41/Not logged into Zooniverse - ERROR CONFIRMED
* Mac OSX Yosemite/Chrome 46/Not logged into Zooniverse - No error
* Mac OSX Yosemite/Firefox 42/Not logged into Zooniverse - ERROR CONFIRMED

**Comment by simoneduca** [comment]
If animation is disabled the problem disappears. When I tested on FF before and couldn't reproduce. I then upgraded to v42 and I can see the issue. Some breaking change happened. I think support for `transform` might have changed.

**Comment by rogerhutchings** [comment]
Might fix it: https://developer.mozilla.org/en/docs/Web/CSS/transform-origin

**Comment by simoneduca** [comment]
Cheers @rogerhutchings. It looks like Moz folks haven't made up their minds yet.
https://bugzilla.mozilla.org/show_bug.cgi?id=1209061

**Comment by shaunanoordin** [comment]
Confirmed: Firefox is topsy-turvy with transform-origin.

Behaviour in Chrome 46 and Opera 33:
* Default is transform-origin: center center 0, equivalent to transform-origin: 50% 50% 0px
* transform-origin: percentage% percentage% is relative to the *bounding box* of the SVG element.
  * e.g. transform-origin: 100% 0% 0 = upper right corner of SVG element.
* transform-origin: absolute.px absolute.px is relative to the *parent (root?)* of the SVG element.

Behaviour in Firefox 42:
* Firefox ignores *percentage%*, (turning them into 0px,) but acknowledges *absolute* length/dimension values.
* Default is ostensibly transform-origin: 0px 0px 0 - the upper-left corner of the parent (root?) SVG element.

Now how do I link this with #155 ?

Tester:
[svg-tester.html.txt](https://github.com/zooniverse/shakespeares_world/files/33165/svg-tester.html.txt)
(Rename to HTML)

**Comment by rogerhutchings** [comment]
I don't think the two issues are linked.

As FF doesn't implement `transform-origin` yet, the most cross-browser compatible way to do this is probably a JS animation, annoyingly.
