### ISSUE TITLE
dates/working on the "About" page should change

### ISSUE THREAD

**Issue by pding001** [zooniverse/shakespeares_world#144]
This is a minor thing, *but* while the dates for Shakespeare's lifespan are correct on the "About" page, it might be misleading to users since several of the manuscripts are from much later in the seventeenth century or earlier in the sixteenth. Could we say something instead like:
"In this project we're inviting you to work with images of manuscript documents created in the sixteenth and seventeenth centuries."
Shakespeare's lifespan could be mentioned in the next paragraph about 1616 and the time of this death.

**Comment by VVH** [comment]
I used the phrase 'documents created in and around Shakespeare’s lifetime' to indicate that the documents are not strictly limited to his lifetime. I don't think it is necessary to change this.
