### ISSUE TITLE
Implement previous/next subject (ON HOLD)

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#168]
If feature is a requirement then I need the following.

Check the context of retired/already seen for non-queued routes.

The functionality isn't on a normal subjects route, but it can be with params override.

​E.g. `get /subjects/1?context=retired_status` or something

Also make sure that when you flip the pages(`get /subjects/1`), I get a retired attribute on the subject response object.

**Comment by rogerhutchings** [comment]
...when did this happen?

**Comment by rogerhutchings** [comment]
Descoped.
