### ISSUE TITLE
detecting foreign language text

### ISSUE THREAD

**Issue by ggdhines** [zooniverse/shakespeares_world#18]
People aren't supposed to enter non English text - but some people do. Using a quick dictionary check we can find if a word is in another language and display a warning message

**Comment by chrislintott** [comment]
Is this going to be problematic for difficult cases e.g. foreign names, or places where a single foreign word is quoted within english? How reliable are dictionaries at the time?

**Comment by ggdhines** [comment]
All good issues that I don't have a perfect response to - that's why I think giving only a warning would be good. (and maybe if only a minimum number of foreign words are detected. We should also specifically ignore place names)
