### ISSUE TITLE
Common Confusions update

### ISSUE THREAD

**Issue by MattKimberley** [zooniverse/shakespeares_world#188]
Update this part of site to reflect new doc (replacing field guide refs with illustrative examples)

**Comment by simoneduca** [comment]
@MattKimberley @VVH is this supposed to be a new section of the guide?

**Comment by simoneduca** [comment]
[CommonConfusions.pdf](https://github.com/zooniverse/shakespeares_world/files/49005/CommonConfusions.pdf)

**Comment by shaunanoordin** [comment]
Document update, from @VVH at 2015.12.02 11:00

[UpdatedCommonConfusions-20151202-1100.pdf](https://github.com/zooniverse/shakespeares_world/files/50027/UpdatedCommonConfusions-20151202-1100.pdf)

**Comment by shaunanoordin** [comment]
Note that I am addting Common Confusions as a new section of the Guide. Its submenu link will be added below Examples of Transcriptions.

Also note that I have not enlarged/shrunk the images in the CC guide; all images were ripped straight from the .doc provided. (Yes, this includes the enlarged 'neglected' and ) The visual design will be updated if a stakeholder - @VVH ? - requests specific changes.
