### ISSUE TITLE
Make the project name link on the Project Builder link back to SW website

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#189]
In the top left banner of any project built in the PB you see the project name. When you click on this it brings you to the homepage of that project. Any custom projects using Talk need to change that link to point to the project website, otherwise people can see whatever random workflow you have under the hood or get lost classifying subjects that they are not in fact really contributing meaningful data for. 

If we don't make any change to this people will see the PFE project into which we have loaded the data. It needs a custom redirect from anyone with collaborator status on the project which could be @simoneduca @camallen or @rogerhutchings.

**Comment by camallen** [comment]
anyone with owner / collab rights can edit the redirect url via the api

**Comment by simoneduca** [comment]
I don't have admin rights.

**Comment by VVH** [comment]
Is there a critical difference between admin and collaborator in this case @camallen? If not, you have collab rights already @simoneduca

**Comment by camallen** [comment]
done.
