### ISSUE TITLE
New Bios for OED colleagues

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#192]
Please add: 

Philip Durkin (@PhilipDurkin) is Deputy Chief Editor of the *Oxford English Dictionary*, and has led the dictionary's team of specialists in Etymology for the past sixteen years. He is the author of *The Oxford Guide to Etymology* (2009; paperback 2011), which has quickly become the standard work in the field, and of *Borrowed Words: A History of Loanwords in English* (OUP 2014; paperback 2015), and he is editor of *The Oxford Handbook of Lexicography* (2015).

![philipdurkin](https://cloud.githubusercontent.com/assets/6482891/11528598/bbc118ba-98df-11e5-87a9-86ffaa34fa47.jpg)

James McCracken is Content Technology Manager in the dictionaries department of Oxford University Press. He has worked in lexical data engineering, corpus development, and website architecture, and has been involved in building semantic web resources for digital humanities projects. He was formerly a lexicographer for the *Oxford English Dictionary*.

--

(no image for James)

**Comment by simoneduca** [comment]
@shaunanoordin would you be able to help?

**Comment by shaunanoordin** [comment]
Since Durkin and McCracken don't appear to be part of the Folger Library, (or the Zooniverse team,) I'm creating a third group for them in the Team page: Folger Library, *Oxford English Dictionary*, Zooniverse.

**Comment by shaunanoordin** [comment]
Issue: McCracken's lack of photo means that I need to put a placeholder image for him - in this case a blank white image. I am currently looking for a more elegant solution - e.g. putting an if/else in the Angular that detects a lack of an image.

**Comment by VVH** [comment]
good idea on both of those Shaun. Could you just put the *Oxford English Dictionary* section under Zooniverse though. While you're at it, could you also please change 'Folger Library' to 'Folger Shakespeare Library'
