### ISSUE TITLE
Embed Twitter on site

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#198]
This isn't urgent, but should be done as soon as feasible. The handle is @ShaxWorld.

**Comment by rogerhutchings** [comment]
What does embedding mean? Adding a link? Adding a widget with the last few tweets?

**Comment by VVH** [comment]
Projects that have a social media account, ie Penguin Watch, Galaxy Zoo, Science Gossip (most of them probably) have twitter, fb and g+ icons on the home page that take you to the relevant page. So, 
![screen shot 2015-12-08 at 10 30 28](https://cloud.githubusercontent.com/assets/6482891/11653516/ba4167e0-9d96-11e5-996e-469eec4b0206.png) takes you to
![screen shot 2015-12-08 at 10 30 54](https://cloud.githubusercontent.com/assets/6482891/11653538/ce4b45ee-9d96-11e5-84df-852973dcd0e9.png)

**Comment by simoneduca** [comment]
Link https://twitter.com/search?q=%40shaxworld&src=typd
