### ISSUE TITLE
Logos 

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#201]
Please embed logos in this order horizontally in the green banner: 

1) Zooniverse  2) Folger 3) EMMO [4) OED if we get it]

![folg_core_2c](https://cloud.githubusercontent.com/assets/6482891/11568158/872e16d0-99e2-11e5-97a2-ffda63217a33.jpg)
![fsl-emmologo-vfinal-2colorblue](https://cloud.githubusercontent.com/assets/6482891/11568163/89c8c552-99e2-11e5-99f1-3f354f7bbd8e.jpg)

All logos should link to relevant website: 

Zoo: https://www.zooniverse.org/

Folger: www.folger.edu

EMMO: http://folgerpedia.folger.edu/Early_Modern_Manuscripts_Online_(EMMO)

--

Re: Zoo logo: I think it would make most sense to increase the size of our logo, cut the text under it or make it smaller, and move it to the left. We already have a link to Zoo home further down the page. .

Another thought on sizing and logo visibility is that there is a lot of space between the 'get started' area, the genre circles and the bottom. If while you are doing logos it is easy and sensible to reduce that space, that would be nice. Don't worry if not.

**Comment by shaunanoordin** [comment]
Banner will be placed above "Choose a genre and start transcribing!"

Order of logos will be: Zooniverse, Folger, Emmo

Layout will be similar to http://www.operationwardiary.org/

**Comment by rogerhutchings** [comment]
I would suggest placing them below, as they're less important

**Comment by simoneduca** [comment]
Yes. I think just below the choose genre section is a good comprise.

**Comment by shaunanoordin** [comment]
Acknowledged - below they will go!

![zooniverse-20151208-shakespeares-logo](https://cloud.githubusercontent.com/assets/13952701/11654407/43b8d674-9d9d-11e5-97e6-dd7514dcb2b0.png)

**Comment by VVH** [comment]
This just in: I just received the OED logo. It should go in at some point, but if it can't be before launch, then that's ok. 
![oed header](https://cloud.githubusercontent.com/assets/6482891/11655219/cc6a0afa-9da3-11e5-9531-62194dcdf623.jpg)

with this link: http://www.oed.com/

OED logo should appear on the far right

**Comment by shaunanoordin** [comment]
Stakeholders, please review proposed design. @VVH 

![screen shot 2015-12-08 at 12 52 50](https://cloud.githubusercontent.com/assets/13952701/11656080/aa81419a-9daa-11e5-9c2e-6ab13d6b8462.png)

Why yes, there is a bit of wonkiness when it comes to white backgrounds vs dark backgrounds. I'll see if I can find an amicable solution - if not, I'll need someone to point me to the black version of the big-Zooniverse logo.

**Comment by rogerhutchings** [comment]
What, so they all have nasty backgrounds? No - @VVH, can you source some vector logos (either `.svg` or `.eps`) for Folger / Emmo / OED? If they have 'light text on dark background' versions, great, if not we can create them.

**Comment by simoneduca** [comment]
+1

**Comment by shaunanoordin** [comment]
Proposed edit, design v2.

![screen shot 2015-12-08 at 12 52 50](https://cloud.githubusercontent.com/assets/13952701/11656342/648612d6-9dac-11e5-9079-08a8f1f23195.png)

If unsatisfactory, I'll switch computers and pull out my Photoshop E.

**Comment by simoneduca** [comment]
I think we should get consistent looking logos (heights, colors, backgrounds).

**Comment by shaunanoordin** [comment]
(In case someone can't see the corrected photo: Proposal v2 puts a theme-specific green background & border around all elements.)

Getting a consistent height is possible - as soon I figure out what to do with Emmo.

**Comment by rogerhutchings** [comment]
Can you attach the proper v2, or put it in Slack @shaunanoordin?

Regardless, we should do it properly and get the vector versions.

**Comment by shaunanoordin** [comment]
V2: https://cloud.githubusercontent.com/assets/13952701/11656373/a9d8cae0-9dac-11e5-8c99-ec08cb475860.png

New V3 proposal with white backgrounds:
![screen shot 2015-12-08 at 13 16 08](https://cloud.githubusercontent.com/assets/13952701/11656569/03c9bef0-9dae-11e5-840b-d5518f7aae7d.png)

**Comment by shaunanoordin** [comment]
I'm in agreement with Roger - @VVH, do we have access to the vector files for the Folger, Emmo and OED logos?

For Zooniverse, I assume we can take this: http://www.operationwardiary.org/images/logos/zooniverse-logo.svg

**Comment by shaunanoordin** [comment]
v4 proposal: Acknowledging Simone's point for consistent logos. Unfortunately, we really need an alternative for the OED logo. 

![screen shot 2015-12-08 at 13 50 03](https://cloud.githubusercontent.com/assets/13952701/11657195/c35bc2e6-9db2-11e5-9f00-895e65ef4f41.png)

**Comment by shaunanoordin** [comment]
v5 proposal: rounded containers - Right round baby right round

![screen shot 2015-12-08 at 14 20 26](https://cloud.githubusercontent.com/assets/13952701/11657788/fbd954c2-9db6-11e5-88a6-356b1d64955c.png)

@vvh, please let me know if we can get those logos. If not, I'm switching focus to IE testing now.

**Comment by VVH** [comment]
Hey all, I like v2 best Sorry for not piping up earlier @simoneduca @shaunanoordin
