### ISSUE TITLE
enable login

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#202]
I'm not sure if this is an actual issue or a limitation by design because we don't want people to submit data? 

When I tried to log into SW home (actual site, not preview) I got to this link and this error message: https://panoptes.zooniverse.org/oauth/authorize?response_type=token&client_id=2abed6ac014d4a8416a1f578de922600451a10c759dfeab6c9f0edbeb91c8f88&redirect_uri=http://www.shakespearesworld.org

![screen shot 2015-12-03 at 17 33 16](https://cloud.githubusercontent.com/assets/6482891/11568485/468a6f78-99e4-11e5-84b7-30226fca9786.png)

Log in works on the preview project. 

sanity check @camallen @simoneduca @rogerhutchings

**Comment by camallen** [comment]
looks like the main site is not a valid redirect...actually there is no client there, when did this start happening? @simoneduca did you setup a api client ala old weather?

**Comment by camallen** [comment]
sorry,  i was on the wrong site, fixing now.

**Comment by camallen** [comment]
fixed.
