### ISSUE TITLE
New data_site hanging

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#203]
Mike P is uploading the new data today. We might need to turn on the new data in the workflow on the PB, but I'm not sure.

I've tried loading in Safari and Firefox and the site is hanging for a long time. Not sure if this is a feature of the data being in flux or something else. It reminds me of how AnnoTate behaved on launch though, so extra browser testing is in order. @simoneduca and maybe @shaunanoordin should take a look.

If the site is requesting all of the data for each user, ie 8k that would explain the hang.

**Comment by simoneduca** [comment]
@VVH Most likely this has to do with the new dataset upload.

**Comment by VVH** [comment]
ok, I hope that's all it is! Will do some low level browser testing this weekend.

**Comment by VVH** [comment]
Just checked again @simoneduca and getting a 'no data message' straight away. Have turned on data in the PB but nothing is happening.

**Comment by VVH** [comment]
Also, @rogerhutchings this sounds familiar from AnnoTate I think, so perhaps you can shed some light.

**Comment by VVH** [comment]
Been trying in different browsers (as has Al) and it looks like the out of data message sometimes appears, but if we hit refresh we get a manuscript page. Probably an easy fix.

**Comment by rogerhutchings** [comment]
Fixed by #205
