### ISSUE TITLE
Safari: No image for Step 3 in Tutorial

### ISSUE THREAD

**Issue by MattKimberley** [zooniverse/shakespeares_world#206]
[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (step3.gif, line 0)
(https://static.zooniverse.org/preview.zooniverse.org/folgerdemo/images/tutorial/step3.gif)

**Comment by rogerhutchings** [comment]
Having looked at the markup, there isn't an image at all for this step, just text. The error we can safely ignore.
