### ISSUE TITLE
Safari: 403 when transcribing text

### ISSUE THREAD

**Issue by MattKimberley** [zooniverse/shakespeares_world#207]
Having clicked on Transcribe Text, the following appears after saving changes (examples):

[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (.txt, line 0) (https://static.zooniverse.org/www.shakespearesworld.org/variants/.txt)

[Error] Failed to load resource: the server responded with a status of 403 (Forbidden) (nomino.txt, line 0)
(https://static.zooniverse.org/www.shakespearesworld.org/variants/nomino.txt)

**Comment by simoneduca** [comment]
@MattKimberley  The behaviour is expected. It means that new variants may have been found. But the errors should only show in browser dev console. Where did you see the error messages?

**Comment by MattKimberley** [comment]
That's okay then, it was in dev console.
