### ISSUE TITLE
URL anchor

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#21]
Change the URL to have an # anchor as in http://preview.zooniverse.org/folgerdemo/#/transcribe otherwise 404 error when refreshing the page

**Comment by rogerhutchings** [comment]
https://github.com/zooniverse/shakespeares_world/blob/master/app/modules/app.config.js#L12

**Comment by simoneduca** [comment]
@rogerhutchings as far as I understand when html5Mode is enabled, the # character will no longer be used in the urls. Although urls look nicer without #, using html5mode requires server side rewrites.
Did you disable html5mode here http://preview.zooniverse.org/transcribe/#/ (btw is that the most recent version of Annotate)? And, are you suggesting I should do the same?

**Comment by rogerhutchings** [comment]
Pretty sure it's something to do with Angular running out of an S3 subfolder. Just setting that to false should fix it

**Comment by simoneduca** [comment]
It does indeed, thanks.
