### ISSUE TITLE
New tutorial prose and images.

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#216]
Please use the pdf document I sent at 3:33pm via email it should go as a pdf (as is) into the Field Guide under a tab called 'Tutorial'

The tutorial modals should use the images and text from this googledoc: https://docs.google.com/document/d/1xDt-iJJ5wvG9rWd-grWUpplvMi1SIqiZpCAtfTFK1cw/edit

**Comment by simoneduca** [comment]
This is the new static pdf 
[Tutorial_SW_FINAL.pdf](https://github.com/zooniverse/shakespeares_world/files/56970/Tutorial_SW_FINAL.pdf)
to upload as a section of the guide.
