### ISSUE TITLE
Make sure tutorial modal fits in viewport

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#224]

**Comment by VVH** [comment]
@simone this is the new, prose and images https://docs.google.com/document/d/1xDt-iJJ5wvG9rWd-grWUpplvMi1SIqiZpCAtfTFK1cw/edit

**Comment by VVH** [comment]
This is the new static pdf 
[Tutorial_SW_FINAL.pdf](https://github.com/zooniverse/shakespeares_world/files/56970/Tutorial_SW_FINAL.pdf)
to upload to field guide.
