### ISSUE TITLE
Several tutorial images not showing in Safari

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#235]
![screen shot 2015-12-10 at 10 52 16](https://cloud.githubusercontent.com/assets/6482891/11713577/270ad53c-9f2c-11e5-9890-102605f1415c.png)

**Comment by VVH** [comment]
Specifically 3—11.

**Comment by simoneduca** [comment]
File names started with a capital. I changed that to lowercase and that fixed it.
