### ISSUE TITLE
Transcribe box obscures the line i want to transcribe

### ISSUE THREAD

**Issue by camallen** [zooniverse/shakespeares_world#247]
i find it breaks my flow from mouse / keyboard transcription.

**Comment by VVH** [comment]
A user has commented on this too. If we could get the transcription box to centre between the dots, that would help.

**Comment by VVH** [comment]
Suggestion: get box to centre between the two dots and also to appear slightly further down, maybe half an inch, which should mean people won't have to move it in too many cases.
