### ISSUE TITLE
Change classification count

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#249]
If we have time for this, it would be great if we could change the classification count to report users' annotations per page instead of number of pages they've seen on a transcription project. You see the classification count on the Zoo home profile. @camallen thinks that is doable, but not sure about time. It's a nice to have, but certainly would improve user experience and be nice to introduce it down the line @simoneduca if we think there's an opportunity to do so.

**Comment by camallen** [comment]
basically submit 1 classification per annotation / line.
