### ISSUE TITLE
cursor should automatically go into transcription box

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#252]
a few users and @marten have commented on this and it would be an easy win. I don't see Marten's issue, but it's probably because I'm going crosseyed.

**Comment by rogerhutchings** [comment]
Duplicate of #233

**Comment by rogerhutchings** [comment]
Also, you can search for issues by author: [`author:marten`](https://github.com/zooniverse/shakespeares_world/issues?utf8=%E2%9C%93&q=author%3Amarten+) in the search box
