### ISSUE TITLE
URL query params break the site

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/shakespeares_world#253]
Looks like the transcription interface doesn't work if you follow the link from the launch email, which has a bunch of tracking params.
http://www.shakespearesworld.org/?utm_source=Newsletter&utm_medium=Email&utm_campaign=SWorldLaunch#/transcribe

Talk discussion here: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/20628/

I can reproduce this in Chrome on OSX Yosemite.

**Comment by marten** [comment]
I *can* classify if I follow that link. But the login button doesn't react to clicks.

**Comment by camallen** [comment]
@rogerhutchings wasn't this the bug you fixed on old weather the other day? https://github.com/zooniverse/old-weather/commit/540c68506bd81c2a2fd41fd03defc2c1bbb2bb76

**Comment by rogerhutchings** [comment]
Yup, just deployed a fix via e0c82a85ebd96b7cb4f175676d5b918b8eb94afa

**Comment by camallen** [comment]
nice one!
