### ISSUE TITLE
Guide and possible team and about should open in new tabs

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#255]
The guide should probably open in a new tab while you are in the transcription interface. A user reported that when they opened the guide and thus navigated away from their transcription, when they tried to go back they had lost what they were working on and had a new page. I think this is an easy fix and worth doing @simoneduca if you have time on 11 December? https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/20664/?comment=42304

**Comment by simoneduca** [comment]
@VVH I can see the rationale behind opening the guide in a new tab, but I can't say the same for team or about pages.
