### ISSUE TITLE
A few (related?) bugs_buttons not toggling on, page unresponsive to clicks

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#258]
I think there are a few bugs that are somehow related. When users refresh or sign out and sign back in the bugs seem to clear, but it would be good to figure out what's causing the issues. Sorry not to be more specific, but I think there is something @simoneduca is already aware of to do with refreshing which is affecting a number of different things. See this thread for a variety: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/20628?comment=42358&page=2

**Comment by simoneduca** [comment]
Closing as not really an issue.
