### ISSUE TITLE
Add cache busting to the source index.html

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#263]

**Comment by rogerhutchings** [comment]
HTML shouldn't be cached, or should at least have a very short expires header. What's the issue?

**Comment by rogerhutchings** [comment]
Oh, nvm, just caught up on slack

**Comment by rogerhutchings** [comment]
Nope, wait, can't find it now. Nevermind, node-s3-client should set these properly anyway. Closing
