### ISSUE TITLE
Preload keypad images

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#27]

**Comment by simoneduca** [comment]
I am using promises to preload the special characters images in the transcription keypad.

![screen shot 2015-08-25 at 12 31 53](https://cloud.githubusercontent.com/assets/8989606/9465538/58915f5a-4b25-11e5-80d7-6f2e86a869b2.png)

For testing I'm trying with just an image and hardcoding its path on static.zooniverse server.

Locally it's fine and the promise gets resolved.
But when I deploy to http://preview.zooniverse.org/folgerdemo/, I get a 403 Forbidden:

![screen shot 2015-08-25 at 12 32 55](https://cloud.githubusercontent.com/assets/8989606/9465583/b9ce73a2-4b25-11e5-9d56-9c2ca705bb73.png)

**Comment by eatyourgreens** [comment]
Check your image URL. You're requesting
http://preview.zooniverse.org/images/keypad/anno.png
instead of
http://preview.zooniverse.org/folgerdemo/images/keypad/anno.png

**Comment by simoneduca** [comment]
Doh, thanks @eatyourgreens. However I need to sort out the paths in a different way, because if I add '/folgerdemo/' the promise get rejected.

**Comment by eatyourgreens** [comment]
Will the promise work with relative URLs? Maybe drop the initial / from the URL and request something like `images/keypad/anno.png`

**Comment by simoneduca** [comment]
That did it, thanks Jim. I'll try to loop through the entire array now.
