### ISSUE TITLE
Cribsheet not saving snippets between sessions

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#273]
Jules, one of our mods, has reported this as an ongoing problem. She writes: 'the crib sheet still loses its contents unfortunately when either I close SW down or even if I just go to Talk and then click to go back to classifying. If I leave a tab open it's OK but that's not really practical. Otherwise the interface is really nice to use - and the idea of the crib sheet is genius.' 

@rogerhutchings do you think this is likely to be a user issue or us? My cribsheet is working. Jules is on Linux/Mint I believe.

**Comment by VVH** [comment]
Been a few updates on this: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/20629?comment=46361. I've got the cribsheet working in Chrome, so not sure why it's not working for Jules.

**Comment by rogerhutchings** [comment]
Asked Jules about any extensions she's running in Chrome, but if it's not that I'm slightly out of ideas, as it seems to be working for everyone else. Could get her to log the output of the Network tab, I suppose?

**Comment by rogerhutchings** [comment]
I'm going to have to close this one - I've tried out Linux Mint and Chrome, and can save a snippet. She's disabled all extensions, and that didn't make a difference. I've asked her to check the console to see what's going on, but without something to check there's not a lot I can do. And no one else has logged this issue.
