### ISSUE TITLE
Page turning_continuous view

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#281]
@camallen @simoneduca can we try to budget some time for this in the next 8 weeks?

**Comment by camallen** [comment]
Do we have the required metadata to re-construct the zooniverse subject path (i.e. next / prev page) through the original volumes?

**Comment by eatyourgreens** [comment]
Previous subject as a linked resource on the subject would be super useful for Wellcome too. Is there an issue on Panoptes for this?

In the meantime, I'm hacking around this by maintaining an array of 3 subjects at a time to show in the classifier: zooniverse/wellcome/pull/61

**Comment by camallen** [comment]
Nope - it's really a metadata hack on the subject to list the linked internal id's. We could look at adding a partial metadata index to subjects an expose this through the api if it's a common use case.

**Comment by VVH** [comment]
When Folger uploaded their data they included a priority field which enables to list all manuscripts in order within a genre. So recipes goes 1-N and letters goes 1-N. Does that work?

**Comment by camallen** [comment]
Yeah, that is what we need. Great!

**Comment by VVH** [comment]
Hey @camallen and @eatyourgreens is this something that we could implement this month? Folger and our users would love it. Is there time in the schedule?

**Comment by camallen** [comment]
Not really. It's both a backend data thing (provide the subject id for the next/prev page) and front end work to actually fetch the data / turn the pages.
