### ISSUE TITLE
blue dots disappearing between sessions

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#290]
@rogerhutchings @simoneduca can you please investigate this new issue. Is it possible that the version bump or oauth changes have made a knock on effect?

**Comment by rogerhutchings** [comment]
Please submit a full bug report - browsers, steps to recreate, etc

**Comment by VVH** [comment]
As ever, there is a thread on Talk, but minimal detail re: browsers. I would appreciate if you could talk to users directly. I've pinged you on the relevant conversation already, but here it is: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/50402?comment=101051&page=1.

**Comment by VVH** [comment]
@simoneduca or @camallen any ideas?

**Comment by VVH** [comment]
An update from one user, who says she's using Windows 10, Firefox 45.0.2. https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/21281?comment=99397&page=1

**Comment by camallen** [comment]
I can reproduce this (chrome[logged in] and firefox[anonymous]), I transcribe, I see the dots appear and I see the annotations stored in local storage but when i reload the page the dots do not appear again even thought they are still in local storage.

Did the site previously show the dots between sessions / page loads?

**Comment by VVH** [comment]
It did. You could work on a page, not click 'I'm done' and then return to it later so long as it didn't get completed by other people.

**Comment by VVH** [comment]
We've had an update on this re: the grey dots disappearing: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/192/59105?comment=116607. 
People can see the grey dots the first time they see a page, but if they leave and come back to it, the dots disappear. Read the interesting thread on Talk to see what users have to say about their way of working and why this is problematic. 

@astopy says he thinks that this might be something we can quickly fix. Does anyone have the bandwidth to help me out on this, and if so, when? @rogerhutchings @simoneduca?

**Comment by astopy** [comment]
My assumption is that the aggregations aren't being saved in local storage when the subject is loaded the first time, and aren't being fetched from the API the second  time (when the rest of the subject data is loaded from local storage).

<img width="959" alt="screen shot 2016-06-07 at 15 44 22" src="https://cloud.githubusercontent.com/assets/428423/15862328/443e62b2-2cc7-11e6-880e-116ece3a7188.png">

There's no sign of aggregation data in local storage.

**Comment by rogerhutchings** [comment]
That's weird, it should be requesting the aggregations each time. You wouldn't want to save them locally as they might change between transcription sessions

**Comment by astopy** [comment]
Ah yeah, on closer inspection it is requesting the aggregations, but not displaying them.

**Comment by astopy** [comment]
Could it be incorrectly looking in local storage for _everything_ when it renders the subject, even though it's requested the aggregations from the API?

**Comment by VVH** [comment]
Hey @simoneduca when can you spend time on this and do you think that @astopy's suggestion might be the answer?

**Comment by simoneduca** [comment]
@VVH today I spent some time on it and Rog and I sorted a few things out. This problem is still unclear though. I'll spend some more time on it on Monday.
@astopy I thought the aggregated data wasn't called on refresh, but it actually does. `_getAggregations(params)` which talk directly to the API is aslo called on refresh.
However I've managed to reproduce this issue locally, so there's hope :)

**Comment by VVH** [comment]
Some updated concerns from Talk: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/41673?page=1
