### ISSUE TITLE
pdf truncated

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#292]
Jules (a moderator) and others are having [this issue](https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/51760). I've reproduced it on Chrome 50.0.2661.86 (64-bit) and Mac 10.10.5.

**Comment by simoneduca** [comment]
This is lower priority than the other issues in this milestone.

**Comment by VVH** [comment]
Hey @simoneduca, a few users keep having this experience of trying to download a pdf of their transcriptions and not being able to. Would it be hard to just delete the functionality?

**Comment by simoneduca** [comment]
That should be straightforward.

**Comment by VVH** [comment]
Ok, thanks.

**Comment by simoneduca** [comment]
@VVH would you like me to remove it?

**Comment by VVH** [comment]
Yes please.

**Comment by simoneduca** [comment]
Done
