### ISSUE TITLE
Build process is weirdly messed up and takes ages

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/shakespeares_world#297]
...so here's a good one. Production builds for SW take ages, but I can't pin down why; there's something in the `browserify` gulp task that's leaving a file handle open or something.

I put in a hack to make it finish properly, and then the _deploy_ process started taking ages. Only to production. Not sure why, and don't particularly want to re-run it because things are working for now.

I'd be interested in having a go at replacing gulp etc with webpack and the AWS cli tool.

**Comment by rogerhutchings** [comment]
This got revisited today - I tried uploading a few times to a test bucket, which completed with 2 minutes. @astopy confirmed it was due to the `variants` folder in the production bucket being indexed, and the thousands of little files it contains slowing down that process. The `browserify` task isn't to blame.

We could: 
- Move `variants` to its own bucket
- Try switching out the `node-s3` package for the AWS SDK, which has an `exclude` option (the docs imply that it only applies to the local source folder though)
- Change the current build script to upload the files individually, although this means the entire project has to be uploaded, not just the changed files. (Unless we can then do a hash of each file for comparison, but having an external client is supposed to save you the bother)

@astopy said he could look at moving the `variants` to their own bucket next week, and it will presumably need some code changes from @simoneduca to look things up from the right bucket? Not sure how that bit of the project works.

**Comment by astopy** [comment]
I'm copying the variants over to https://variants.shakespearesworld.org/ now. It'll probably take a while, but I'll let you know when it's finished.

**Comment by astopy** [comment]
That's done copying now. I'll delete the originals once the front end is updated with the new location.

**Comment by simoneduca** [comment]
@astopy the frontend is updated. Mind removing the variants folder, both from preview.zooniverse.org/shakespearesworld/ and www.shakespearesworld.org please?

**Comment by astopy** [comment]
The old variants folders are gone now

**Comment by simoneduca** [comment]
Thanks

**Comment by simoneduca** [comment]
Just to confirm that moving the variants folder to its own directory fixed the deploy task.
