### ISSUE TITLE
Agree a keyboard and tagset with Folger partners

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#3]
Tagset sent over by Paul Dingman on 8 June 2015, to be discussed at a meeting on 10 June 2015:

·         Insertion
·         Deletion
·         Illegible/gap
·         Unsure/unclear (for later review by an expert paleographer)
·         Expansion (or possibly Abbrev, and leave abbreviated form)
·         Graphic
·         Metamark (controlled vocabulary) [see: http://www.tei-c.org/release/doc/tei-p5-doc/en/html/PH.html#PH-meta] 
·         Addition (to identify bookseller/library marks)
·         Marginalia

**Comment by simoneduca** [comment]
Superseded by #55
