### ISSUE TITLE
IE11 shows blank page

### ISSUE THREAD

**Issue by shaunanoordin** [zooniverse/shakespeares_world#303]
Issue: when visiting https://www.shakespearesworld.org/ using IE11, we are greeted by a blank page. 
Analysis:
* Error message: 'Promise' is undefined
* Looks like our polyfills are out of whack

**Comment by simoneduca** [comment]
This is odd. We fixed a similar issue a year ago for Annotate https://github.com/zooniverse/AnnoTate/issues/194

Annotate also currently shows a blank page with the promise error. 
@rogerhutchings sounds like some changes in the PJC have broken this again?
