### ISSUE TITLE
Page not loading (quickly)

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#308]
I got this error message today after the site and Talk took 20 minutes to load. Looking at dev tools, network I see: 'Refused to display https://panoptes.zooniverse.org/users/sign_in#/' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN''. @simoneduca or @rogerhutchings do you know if this is linked to any recent OAUTH changes? @srallen thinks this might be the issue.

**Comment by simoneduca** [comment]
This is expected behaviour. It's because the app uses an iframe to implement oauth. Not sure why it took ages to load for you.
