### ISSUE TITLE
Mouse click doesn't update cursor pos in transcribe text box

### ISSUE THREAD

**Issue by camallen** [zooniverse/shakespeares_world#312]
Firefox only (it seems), when I mouse click in the transcribe text box does not update the cursor position. Keybindings work fine. Chrome works fine for both.

OS X (10.11.6) laptop using FF 49.

**Comment by eatyourgreens** [comment]
I'm also finding it's impossible to select text, in order to apply the Expansion, Insertion, Deletion etc. tags in FF 49.

Maybe that box should be using a `textarea` rather than `div[contentEditable]`?

**Comment by rogerhutchings** [comment]
IIRC it's using a `div` to enable the content inside to be styled, which you can't do with a `textarea`. Using the latter and showing the raw tags would be an option, but it would make the text input quite noisy

**Comment by simoneduca** [comment]
A`div[contenteditable]` was chosen to allow styling, which was required by Folger. Showing the raw tags, a la Annotate, does indeed look very messy in the case of SW, given the number of different tags. Not really sure how to fix this, but this might be it http://stackoverflow.com/questions/27093136/firefox-contenteditable-cursor-issue
