### ISSUE TITLE
Transcriptions recorded with wrong subject ID

### ISSUE THREAD

**Issue by astopy** [zooniverse/shakespeares_world#315]
Some transcriptions appear to be mismatched in the classifications output. E.g. look at the classifications for the subject `1278284`. As far as I can see this must be happening in the front end somehow.

**Comment by VVH** [comment]
I've checked that the Folger unique identifiers are in fact all unique. They are. This means that the mismatching has to do with something at our end, possibly in the generation of Zooniverse IDs or something else. @camallen @marten could this have anything to do with the bug we were seeing in the last year or so where subjects from one project would show up in the interface or Talk of another?

**Comment by camallen** [comment]
Subject id is provided by the front end on classification, backend just uses that data.

**Comment by simoneduca** [comment]
This is an example of mismatch for the same subject id. The first classification has the correct text, while the second gets it wrong 

`11137786,Stickywarp,4842,c8f903a2248f657f71ee,205,Subject type,10.14,2016-04-09 15:20:59 UTC,,,"{""started_at"":""2016-04-09T11:20:46-04:00"",""user_agent"":""Shakespeare's World"",""finished_at"":""2016-04-09T11:20:58-04:00"",""live_project"":true,""user_language"":""en_GB"",""user_group_ids"":[]}","[{""task"":""T0"",""value"":false},{""task"":""T2"",""value"":[{""text"":""153 \u0026nbsp;are enough take them out and when they are colde keepe them in boxes, you maye leave out the ginger"",""type"":""text"",""complete"":true,""endPoint"":{""x"":726.09,""y"":101.86},""variants"":["""",""boxes"",""""],""startPoint"":{""x"":54.54,""y"":73.18}},{""text"":""To make Seed cakes or Biskets."",""type"":""text"",""complete"":true,""endPoint"":{""x"":816.06,""y"":161.85},""variants"":[""biskets"",""cakes""],""startPoint"":{""x"":293.17,""y"":160.54}},{""type"":""text"",""complete"":true,""endPoint"":{""x"":1096.41,""y"":301.37},""startPoint"":{""x"":162.77,""y"":203.57}}]},{""task"":""T3"",""value"":false}]","{""1278284"":{""retired"":{""id"":1758707,""workflow_id"":205,""classifications_count"":10,""created_at"":""2016-03-02T20:07:27.024Z"",""updated_at"":""2016-09-24T00:29:44.656Z"",""retired_at"":""2016-09-24T00:29:44.645Z"",""subject_id"":1278284,""retirement_reason"":null},""Genre"":""Letters"",""Title"":""To Walter Bagot and Walter Chetwynd, later Sir Walter Chetwynd. Stafford Castle."",""Author"":""Stafford, Edward Stafford, 12th Baron"",""Origin"":""May 6, 1597(?)."",""Filename"":""41477.jpg"",""Luna URL"":""http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~568286~139168"",""Priority"":""2814"",""Page Sort"":""0"",""Hamnet URL"":""http://hamnet.folger.edu/cgi-bin/Pwebrecon.cgi?BBID=230544"",""Call Number"":""L.a.874"",""Page Number"":""fol. 2v""}}",1278284`


`10956073,carl801,3697,eda08ee06318671f00b4,205,Subject type,10.14,2016-04-01 18:35:24 UTC,,,"{""started_at"":""2016-04-01T13:32:46-05:00"",""user_agent"":""Shakespeare's World"",""finished_at"":""2016-04-01T13:35:24-05:00"",""live_project"":true,""user_language"":""en_GB"",""user_group_ids"":[]}","[{""task"":""T0"",""value"":false},{""task"":""T2"",""value"":[{""text"":""To the Wurshipfull Water Bagot \u0026amp; Water Chetwynd Esquyres"",""type"":""text"",""complete"":true,""endPoint"":{""x"":189.34,""y"":802.63},""variants"":[""wurshipfull"",""chetwynd"",""esquyres"",""bagot""],""startPoint"":{""x"":628.64,""y"":847.44}}]},{""task"":""T3"",""value"":true}]","{""1278284"":{""retired"":{""id"":1758707,""workflow_id"":205,""classifications_count"":10,""created_at"":""2016-03-02T20:07:27.024Z"",""updated_at"":""2016-09-24T00:29:44.656Z"",""retired_at"":""2016-09-24T00:29:44.645Z"",""subject_id"":1278284,""retirement_reason"":null},""Genre"":""Letters"",""Title"":""To Walter Bagot and Walter Chetwynd, later Sir Walter Chetwynd. Stafford Castle."",""Author"":""Stafford, Edward Stafford, 12th Baron"",""Origin"":""May 6, 1597(?)."",""Filename"":""41477.jpg"",""Luna URL"":""http://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~568286~139168"",""Priority"":""2814"",""Page Sort"":""0"",""Hamnet URL"":""http://hamnet.folger.edu/cgi-bin/Pwebrecon.cgi?BBID=230544"",""Call Number"":""L.a.874"",""Page Number"":""fol. 2v""}}",1278284
 `

**Comment by simoneduca** [comment]
After looking at the export, I've made about 20 classifications and looked at the relevant log message. I wasn't able to find evidence of mismatching:

1. subject id
2. location url

I then looked at the timestamp of the problematic classification: `2016-04-09`, which is quite old. Also that subject has been retired, which means that I will have to look at more recent subject and check if there's still something wrong.

My hypothesis is that a refactor of the subject loader (last June) has fixed this issue, but I'll check the more recent classifications for evidence.

In the meantime, some help would be amazing in looking at the classification csv.

**Comment by VVH** [comment]
@astopy has the latest on the csv data. How's that going?

**Comment by astopy** [comment]
@vvh I'm working on the aggregation CSVs. @simoneduca is talking about the classification CSVs.

**Comment by simoneduca** [comment]
@astopy however the aggregations CSVs can tell us really quickly if there are mismatch: the measures would be very off for a mismatch, right? So is there any chance that you can look for something like that in some recent data (after July anyway)

**Comment by simoneduca** [comment]
@camallen I'm not sure that's right: the app gets subjects from panoptes and the puts the same subject id into the classification object which gets sent to back to panoptes.

**Comment by camallen** [comment]
The classification payload has to include a subject id (as you describe) the back end doesn't care what subject id is sent though (as long as its valid). it'll record whatever you send in the payload.

**Comment by simoneduca** [comment]
I've checked more recent raw data (classifications) for id mismatch and could not find evidence of it. Closing this for now, but happy to reopen if needed.
