### ISSUE TITLE
change 'guide' to 'how to transcribe' on home page tabs

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#318]
Various volunteers have suggested that we change the name of this tab so that people are more likely to find and use the additional information on the site, and make their transcriptions better. I think it's a small change worth making. More [here](https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/195/154452?comment=274805&page=1). @shaunanoordin is this something you could do? Or @simoneduca?

**Comment by shaunanoordin** [comment]
No worries, can be done.
