### ISSUE TITLE
Fetch aggregation data from Caesar

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/shakespeares_world#344]
This would fetch data for aggregated points generated by @CKrawczyk's new aggregation engine, delivered by Caesar. This replaces the existing aggregation data provided via the API aggregations endpoint.

## Proposed Implementation

- Minimum number of views and consensus score threshold gets set on the main SW workflow in the `configuration` property: 

    ```
    {
         min_number_views: 4,
         min_consensus_score: 3
    }
    ```

- Add a GraphQL client to SW (@marten suggested [graphql-request](https://github.com/graphcool/graphql-request) or [lokka](https://github.com/kadirahq/lokka).
- Request is made with the subject and workflow IDs, as it is now.
- Response consists of an array of objects, each representing a line. Those with `number_views` and `consensus_score` below those values set in the workflow configuration get chucked.
- Of the remainder, the points are derived from `clusters_x` and `clusters_y` properties, as they are now.

## Notes

- There's no auth with Caesar to worry about.
- By setting the thresholds on the workflow, we don't need to worry about redeploying code to modify them later.
- The only functions that really need changing in  [aggregations.factory.js](https://github.com/zooniverse/shakespeares_world/blob/master/app/modules/transcribe/aggregations/aggregations.factory.js) are `_getAggregations` and `_formatAggregations`.

## Questions

- What's the URL of the endpoint?
- What does the query look like? I'm guessing something like:

    ```
    `{
        Aggregation(workflow_id: 123, subject_id: 456) {
            frame0 {
                clusters_x
                clusters_y
                consensus_score
                number_views
            } 
        }
    }`
    ```

## Links

- [Aggregations factory in SW](https://github.com/zooniverse/shakespeares_world/blob/master/app/modules/transcribe/aggregations/aggregations.factory.js) (yes, Angular calls things factories when they're not)
- [Example response data](https://github.com/zooniverse/aggregation-for-caesar/blob/master/panoptes_aggregation/tests/reducer_tests/test_sw_reducer.py#L694-L932)

## Estimated time

I reckon this shouldn't take more than a day, so I'm saying **two days**.

cc @marten, @chrislintott

**Comment by marten** [comment]
The endpoint is `https://caesar.zooniverse.org/graphql`. (Or caesar-staging.zooniverse.org)

The contents of the aggregations vary wildly per reducer type, and I don't see how we could make those part of the GraphQL schema, sadly. So the query would be:

```graphql
query Aggregation($workflowId: ID!, $subjectId: ID!) {
  workflow(id: $workflowId) {
    reductions(subjectId: $subjectId){
      data
    }
  }
}
```

(In GraphQL you can send query templates plus a JSON object that assigns variables to values, which is what I'm doing here. This means you don't have to do string concatenation to build queries, which is a common security hole.)

This would return the data you've linked as "example response data" under the "data" key. Something like (possibly I've pulled an outdated sample from staging):

```json```
{
  "data": {
    "workflow": {
      "reductions": [
        {
          "data": {
            "frame0": [
              {
                "clusters_x": [
                  1301.0959692898273,
                  1364.308198519331
                ],
                "clusters_y": [
                  71.80710172744716,
                  62.39251439539345
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "616"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  774.9883880615234,
                  898.9557952880859,
                  1065.5179748535156,
                  1208.271240234375,
                  1292.590576171875,
                  1371.1090087890625
                ],
                "clusters_y": [
                  115.59837913513184,
                  117.06962013244629,
                  116.89728927612305,
                  115.59837913513184,
                  118.3685302734375,
                  110.49104690551758
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 2,
                "clusters_text": [
                  [
                    "John's",
                    "John"
                  ],
                  [
                    "Island",
                    "Leland"
                  ],
                  [
                    "Sept",
                    "Sept"
                  ],
                  [
                    "18th",
                    "18th"
                  ],
                  [
                    "1856",
                    "1856"
                  ],
                  [
                    "",
                    ""
                  ]
                ],
                "consensus_score": 1.6
              },
              {
                "clusters_x": [
                  653.161865234375,
                  780.9276733398438,
                  874.4148559570312,
                  999.064453125,
                  1108.1328125,
                  1220.3175048828125,
                  1394.826904296875
                ],
                "clusters_y": [
                  292.1474914550781,
                  301.4961853027344,
                  292.1474914550781,
                  282.79876708984375,
                  289.03125,
                  285.9150085449219,
                  289.03125
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "Dear"
                  ],
                  [
                    "sir"
                  ],
                  [
                    "I"
                  ],
                  [
                    "have"
                  ],
                  [
                    "just"
                  ],
                  [
                    "received"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  581.4883422851562,
                  861.9498901367188,
                  980.3670043945312,
                  1036.4593505859375,
                  1182.922607421875,
                  1239.014892578125,
                  1366.78076171875
                ],
                "clusters_y": [
                  332.6585998535156,
                  338.8910827636719,
                  329.5423583984375,
                  332.6585998535156,
                  338.8910827636719,
                  338.8910827636719,
                  335.77484130859375
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "information"
                  ],
                  [
                    "that"
                  ],
                  [
                    "a"
                  ],
                  [
                    "fellow"
                  ],
                  [
                    "of"
                  ],
                  [
                    "mine"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  596.448974609375,
                  760.4026489257812,
                  801.8050537109375,
                  969.0709228515625,
                  1098.24658203125,
                  1232.390380859375,
                  1331.7562255859375,
                  1394.68798828125
                ],
                "clusters_y": [
                  383.536376953125,
                  385.1924743652344,
                  385.1924743652344,
                  378.5680847167969,
                  378.5680847167969,
                  385.1924743652344,
                  381.8802795410156,
                  381.8802795410156
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "Moses,"
                  ],
                  [
                    "a"
                  ],
                  [
                    "small"
                  ],
                  [
                    "black"
                  ],
                  [
                    "man"
                  ],
                  [
                    "who"
                  ],
                  [
                    "has"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  589.8245849609375,
                  690.8465576171875,
                  909.451416015625,
                  997.224609375,
                  1113.1513671875,
                  1285.385498046875,
                  1391.3758544921875
                ],
                "clusters_y": [
                  424.9388122558594,
                  429.9071044921875,
                  431.5632019042969,
                  428.2510070800781,
                  424.9388122558594,
                  421.6266174316406,
                  424.9388122558594
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "been"
                  ],
                  [
                    "runaway"
                  ],
                  [
                    "for"
                  ],
                  [
                    "some"
                  ],
                  [
                    "months"
                  ],
                  [
                    "was"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  589.8245849609375,
                  753.7782592773438,
                  831.6148071289062,
                  922.7001953125,
                  1166.146484375,
                  1224.1099853515625,
                  1290.3538818359375,
                  1381.439208984375
                ],
                "clusters_y": [
                  471.3095397949219,
                  474.6217346191406,
                  467.9973449707031,
                  466.34124755859375,
                  467.9973449707031,
                  467.9973449707031,
                  461.3729553222656,
                  467.9973449707031
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "lodged"
                  ],
                  [
                    "in"
                  ],
                  [
                    "the"
                  ],
                  [
                    "workhouse"
                  ],
                  [
                    "or"
                  ],
                  [
                    "at"
                  ],
                  [
                    "least"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  586.9786987304688,
                  730.5126953125,
                  821.7305297851562,
                  883.4367065429688,
                  965.2645263671875,
                  1135.627197265625,
                  1351.598876953125
                ],
                "clusters_y": [
                  510.0069885253906,
                  512.6898803710938,
                  511.3484191894531,
                  510.0069885253906,
                  508.6655578613281,
                  508.6655578613281,
                  508.6655578613281
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "taken"
                  ],
                  [
                    "up"
                  ],
                  [
                    "by"
                  ],
                  [
                    "the"
                  ],
                  [
                    "police"
                  ],
                  [
                    "yesterday"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  584.2958374023438,
                  624.5390014648438,
                  718.439697265625,
                  820.3890991210938,
                  920.9970092773438,
                  1115.505615234375,
                  1179.894775390625,
                  1280.502685546875,
                  1371.720458984375
                ],
                "clusters_y": [
                  559.6402587890625,
                  556.9573364257812,
                  565.0059814453125,
                  556.9573364257812,
                  563.66455078125,
                  558.298828125,
                  560.981689453125,
                  560.981689453125,
                  555.6159057617188
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "I"
                  ],
                  [
                    "took"
                  ],
                  [
                    "him"
                  ],
                  [
                    "last"
                  ],
                  [
                    "February"
                  ],
                  [
                    "at"
                  ],
                  [
                    "$850"
                  ],
                  [
                    "and"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  586.9786987304688,
                  743.9270629882812,
                  882.0952758789062,
                  959.8987426757812,
                  1025.6292724609375,
                  1149.0416259765625,
                  1208.06494140625,
                  1281.8441162109375,
                  1378.427734375
                ],
                "clusters_y": [
                  606.590576171875,
                  603.90771484375,
                  605.2491455078125,
                  601.224853515625,
                  603.90771484375,
                  602.5662841796875,
                  599.8834228515625,
                  598.5419921875,
                  603.90771484375
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "having"
                  ],
                  [
                    "made"
                  ],
                  [
                    "up"
                  ],
                  [
                    "my"
                  ],
                  [
                    "mind"
                  ],
                  [
                    "to"
                  ],
                  [
                    "sell"
                  ],
                  [
                    "him"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  599.7223510742188,
                  781.4873657226562,
                  839.1692504882812,
                  912.9483642578125,
                  992.09326171875,
                  1138.3101806640625,
                  1308.6728515625,
                  1386.476318359375
                ],
                "clusters_y": [
                  652.1995239257812,
                  649.5166625976562,
                  648.1752319335938,
                  642.8094482421875,
                  648.1752319335938,
                  644.15087890625,
                  641.468017578125,
                  642.8094482421875
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "expect"
                  ],
                  [
                    "to"
                  ],
                  [
                    "get"
                  ],
                  [
                    "the"
                  ],
                  [
                    "same"
                  ],
                  [
                    "without"
                  ],
                  [
                    "any"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  581.6129150390625,
                  841.8521118164062,
                  955.8744506835938,
                  1049.775146484375,
                  1189.2847900390625,
                  1288.55126953125,
                  1389.1591796875
                ],
                "clusters_y": [
                  695.1255493164062,
                  687.0769653320312,
                  683.0526123046875,
                  691.1012573242188,
                  680.3697509765625,
                  684.39404296875,
                  687.0769653320312
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "unnecessary"
                  ],
                  [
                    "delay"
                  ],
                  [
                    "but"
                  ],
                  [
                    "would"
                  ],
                  [
                    "take"
                  ],
                  [
                    "$800"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  586.9786987304688,
                  742.5856323242188,
                  849.9007568359375,
                  941.1185913085938,
                  1024.287841796875,
                  1153.06591796875,
                  1263.06396484375,
                  1385.1348876953125
                ],
                "clusters_y": [
                  734.0272827148438,
                  730.0029907226562,
                  731.3444213867188,
                  728.6615600585938,
                  727.3201293945312,
                  727.3201293945312,
                  721.954345703125,
                  728.6615600585938
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "rather"
                  ],
                  [
                    "than"
                  ],
                  [
                    "not"
                  ],
                  [
                    "sell"
                  ],
                  [
                    "him"
                  ],
                  [
                    "the"
                  ],
                  [
                    "bearer"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  579.588623046875,
                  637.2705078125,
                  725.8054809570312,
                  826.4133911132812,
                  1038.3607177734375,
                  1152.383056640625,
                  1226.1622314453125,
                  1271.7711181640625,
                  1316.0386962890625,
                  1397.866455078125
                ],
                "clusters_y": [
                  775.6392211914062,
                  774.2977905273438,
                  772.9563598632812,
                  772.9563598632812,
                  768.9320678710938,
                  771.6149291992188,
                  770.2734985351562,
                  771.6149291992188,
                  766.2491455078125,
                  767.590576171875
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "of"
                  ],
                  [
                    "this"
                  ],
                  [
                    "can"
                  ],
                  [
                    "identify"
                  ],
                  [
                    "him"
                  ],
                  [
                    "he"
                  ],
                  [
                    "is"
                  ],
                  [
                    "a"
                  ],
                  [
                    "prime"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  579.588623046875,
                  737.87841796875,
                  790.1945190429688,
                  940.4357299804688,
                  1042.3851318359375,
                  1157.748779296875,
                  1332.1358642578125
                ],
                "clusters_y": [
                  819.90673828125,
                  818.5653076171875,
                  817.2238159179688,
                  811.8580932617188,
                  814.5409545898438,
                  818.5653076171875,
                  819.90673828125
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "fellow"
                  ],
                  [
                    "of"
                  ],
                  [
                    "twenty"
                  ],
                  [
                    "five"
                  ],
                  [
                    "with"
                  ],
                  [
                    "nothing"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  591.6615600585938,
                  794.2188720703125,
                  872.0223388671875,
                  1032.9949951171875,
                  1149.7001953125,
                  1259.6982421875,
                  1303.9656982421875,
                  1396.5250244140625
                ],
                "clusters_y": [
                  865.515625,
                  862.832763671875,
                  856.1255493164062,
                  853.4426879882812,
                  848.0769653320312,
                  857.467041015625,
                  854.7841186523438,
                  857.467041015625
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "whatever"
                  ],
                  [
                    "the"
                  ],
                  [
                    "matter"
                  ],
                  [
                    "with"
                  ],
                  [
                    "him"
                  ],
                  [
                    "a"
                  ],
                  [
                    "field"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  579.588623046875,
                  669.4650268554688,
                  782.1459350585938,
                  896.168212890625,
                  1011.531982421875,
                  1169.82177734375,
                  1312.0142822265625,
                  1393.8421630859375
                ],
                "clusters_y": [
                  948.6848754882812,
                  944.6605224609375,
                  943.319091796875,
                  943.319091796875,
                  947.3434448242188,
                  944.6605224609375,
                  941.9776611328125,
                  943.319091796875
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "not"
                  ],
                  [
                    "stay"
                  ],
                  [
                    "with"
                  ],
                  [
                    "me"
                  ],
                  [
                    "please"
                  ],
                  [
                    "send"
                  ],
                  [
                    "me"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  582.271484375,
                  631.9047241210938,
                  782.1459350585938,
                  877.3880615234375,
                  943.1185913085938,
                  1054.4580078125,
                  1110.7984619140625,
                  1204.69921875,
                  1348.233154296875,
                  1397.866455078125
                ],
                "clusters_y": [
                  994.2938232421875,
                  988.9280395507812,
                  986.2451782226562,
                  984.9037475585938,
                  987.5866088867188,
                  990.2694702148438,
                  984.9037475585938,
                  984.9037475585938,
                  984.9037475585938,
                  988.9280395507812
                ],
                "line_slope": -0.7734897435762444,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "a"
                  ],
                  [
                    "blank"
                  ],
                  [
                    "bill"
                  ],
                  [
                    "of"
                  ],
                  [
                    "sale"
                  ],
                  [
                    "I"
                  ],
                  [
                    "will"
                  ],
                  [
                    "return"
                  ],
                  [
                    "it"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              }
            ],
            "frame1": [
              {
                "clusters_x": [
                  617.6515502929688,
                  683.0455932617188,
                  835.6317749023438,
                  1030.13720703125,
                  1127.3900146484375,
                  1234.703369140625,
                  1305.127685546875,
                  1358.784423828125
                ],
                "clusters_y": [
                  90.12645721435547,
                  91.80322265625,
                  90.12645721435547,
                  95.15676879882812,
                  95.15676879882812,
                  100.18708038330078,
                  105.21739196777344,
                  103.5406265258789
                ],
                "line_slope": 0.9052725418540494,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "by"
                  ],
                  [
                    "mail"
                  ],
                  [
                    "signed"
                  ],
                  [
                    "write"
                  ],
                  [
                    "and"
                  ],
                  [
                    "let"
                  ],
                  [
                    "me"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  609.2677001953125,
                  733.3487548828125,
                  817.1873168945312,
                  1041.8746337890625,
                  1124.0364990234375,
                  1182.723388671875,
                  1305.127685546875,
                  1387.28955078125
                ],
                "clusters_y": [
                  140.42959594726562,
                  133.72250366210938,
                  138.75282287597656,
                  137.0760498046875,
                  137.0760498046875,
                  143.7831268310547,
                  143.7831268310547,
                  150.49021911621094
                ],
                "line_slope": 0.9052725418540494,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "know"
                  ],
                  [
                    "the"
                  ],
                  [
                    "prospects"
                  ],
                  [
                    "on"
                  ],
                  [
                    "the"
                  ],
                  [
                    "next"
                  ],
                  [
                    "page"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  609.2418823242188,
                  670.5236206054688,
                  713.2274780273438,
                  769.5352783203125,
                  830.6015014648438,
                  874.4876708984375,
                  954.6825561523438,
                  1021.2052917480469,
                  1153.7357177734375,
                  1273.26904296875,
                  1362.137939453125
                ],
                "clusters_y": [
                  195.67633056640625,
                  216.0940704345703,
                  173.9650115966797,
                  218.0742950439453,
                  178.99533081054688,
                  218.0742950439453,
                  182.348876953125,
                  205.69709014892578,
                  207.8689193725586,
                  190.73272705078125,
                  195.76304626464844
                ],
                "line_slope": 0.9052725418540494,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 2,
                "clusters_text": [
                  [
                    "you",
                    "for"
                  ],
                  [
                    "",
                    "the"
                  ],
                  [
                    "will",
                    ""
                  ],
                  [
                    "",
                    "work"
                  ],
                  [
                    "find",
                    ""
                  ],
                  [
                    "",
                    "place"
                  ],
                  [
                    "an",
                    ""
                  ],
                  [
                    "order",
                    "master"
                  ],
                  [
                    "for",
                    ""
                  ],
                  [
                    "Meste",
                    ""
                  ],
                  [
                    "",
                    ""
                  ]
                ],
                "consensus_score": 1
              },
              {
                "clusters_x": [
                  940.8255004882812,
                  1072.510986328125,
                  1322.0203857421875
                ],
                "clusters_y": [
                  273.5208435058594,
                  267.58013916015625,
                  272.5307312011719
                ],
                "line_slope": 0.9052725418540494,
                "slope_label": 0,
                "gutter_label": 0,
                "number_views": 1,
                "clusters_text": [
                  [
                    "yours"
                  ],
                  [
                    "respectfully"
                  ],
                  [
                    ""
                  ]
                ],
                "consensus_score": 1
              }
            ]
          }
        }
      ]
    }
  }
}
```

**Comment by marten** [comment]
One other note, I'll need to set the workflow to have public reductions in Caesar before it works authless.

**Comment by rogerhutchings** [comment]
@marten, [I've added the client](https://github.com/zooniverse/shakespeares_world/blob/new-aggregation-code/app/modules/transcribe/aggregations/aggregations.factory.js), but I'm only getting empty arrays for the reductions. Is my query looking okay, or does the workflow still need public reductions enabling?

**Comment by marten** [comment]
I think that should work. Can you give me an example of a workflow ID and subject ID for which you don't get any data back?

**Comment by marten** [comment]
Oh, and note that we haven't run it over all old subjects yet, just subjects that have recently gotten classifications.

**Comment by rogerhutchings** [comment]
I'm looking at:

```
subjectId: "1278528"
workflowId: "205"
```

It may be that it hasn't been recently classified - have you got a subject ID with some reductions I can test against?

**Comment by marten** [comment]
Try 1276468.
