### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#347]
I am able to log into zooniverse.org/lab and various projects, but not ShaxWorld. Even if I navigate from the project Talk via the 'classify' button, it doesn't let me log in. Thoughts @camallen? When I click on devtools I see: '/#/classify:1 Refused to display 'https://panoptes.zooniverse.org/users/sign_in#!/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.
main.js? [sm]:40279 collapse is now deprecated. Use uib-collapse instead.
(anonymous) @ main.js? [sm]:40279
main.js? [sm]:40279 $modal is now deprecated. Use $uibModal instead.'

**Comment by rogerhutchings** [comment]
I've just tried this, and managed to log in without any issues. Which browser are you using, out of interest?

**Comment by eatyourgreens** [comment]
Should be fixed by zooniverse/panoptes-javascript-client#75.

**Comment by eatyourgreens** [comment]
Fixed in version 2.9 of the Panoptes client. zooniverse/panoptes-javascript-client#75

**Comment by eatyourgreens** [comment]
Closed by #367.
