### ISSUE TITLE
Remove PDF function

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/shakespeares_world#350]
It was commented out, but it should be removed (along with dependencies) if it's not being used.

**Comment by simoneduca** [comment]
Just to clarify: the [pdf code](https://github.com/zooniverse/shakespeares_world/blob/69c464991199b5f8380f332339343fc722529be2/app/modules/transcribe/modals/transcribe-next.controller.js#L43) isn't commented out. It's only the pdf button being hidden.
