### ISSUE TITLE
Users' counters not progressing

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#357]
Volunteers report that their classification counts are not changing despite submitting data. This may account for why they are seeing repeat subjects.

https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/505899?comment=852702&page=1

**Comment by VVH** [comment]
Fascinating: https://www.zooniverse.org/projects/zooniverse/shakespeares-world/talk/194/505899?comment=853144&page=1, it looks like people can unstick their counters in they allow  zooniverse.org, panoptes.zooniverse.org, and www.shakespearesworld.org to store cookies, but then this produces the other bug (#355) we're trying to squash.

**Comment by camallen** [comment]
the bug in #355 isn't related to cookies but to local storage. clearing cookies should not have an effect on this unless they clear the local storage as well.

**Comment by camallen** [comment]
I'm chasing this up on talk as well but i'm not sure how adding those domains is helping. the counts are only shown on the zooniverse.org page. Are stats shown on sw anywhere?

**Comment by VVH** [comment]
I don't think that stats are available for individuals anywhere other than zoo home, but there are garbled project stats at https://www.zooniverse.org/projects/zooniverse/shakespeares-world

**Comment by camallen** [comment]
Garbled? those stats are project wide not per user.

**Comment by VVH** [comment]
I know that those stats are project wide. They are garbled in the sense that they don't accurately reflect overall project progress.

**Comment by camallen** [comment]
@VVH i'm marking this as resolved based on conversations with some users. It seems that logging in with 3rd party cookies disabled was the issue. I know how to ensure folks can login but it requires them whitelisting the login server for the zooniverse (not ideal) in their browser. Put folks that can't login in touch with me via zooniverse DM / Talk and i'll get them working.

We need to fix the underlying oauth client but that's not happening very soon.
