### ISSUE TITLE
Saved graphic annotations don't re-render on page load

### ISSUE THREAD

**Issue by camallen** [zooniverse/shakespeares_world#359]
If i come back to a subject and select to reload my work any saved (local storage) graphic annotations are not reloaded nor drawn on the UI. Instead they are cleared and a new subject is loaded and i lose my work :(

**Comment by simoneduca** [comment]
My bad. This is because graphic annotations are missing a subjectId property against which to check. I'll add that in.

**Comment by simoneduca** [comment]
Mmm turns out adding the `subjectId` gets you the warning when you have unsaved graphic notations, but the drawing is still missing.

**Comment by simoneduca** [comment]
The fact that Annotate is showing the same bug makes me think a library (perhaps `hammerjs` ?) has broken somehow.
