### ISSUE TITLE
Edit Team page. 

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#361]
1) Please create a new alumni section at the bottom of the Team page. 

2) Paul Dingman's new bio: Paul served as the Project Manager for Early Modern Manuscripts Online (EMMO) at the Folger Shakespeare Library until mid 2017. He earned a PhD in History with a concentration in medieval/early modern Europe and is especially interested in cultural history and the digital humanities. Before returning to school to pursue his doctorate, Paul worked for several years in the field of information technology.

3) Elizabeth Tobey's new bio: 'Elizabeth served as a part-time intern on the EMMO Project. She holds a Masters of Library Science degree from the University of Maryland, and a doctoral degree from the University of Maryland in Art History and Archaeology, specializing on the art and social history of the Italian Renaissance.'

4) Can my bio remain where it is but be reworded as follows: 'Victoria served as the Humanities PI of Zooniverse from 2015 to 2018, and is the Co-I of Shakespeare's World with Heather Wolfe. She is an early modernist working on English Catholic women's autobiography in the period when it was illegal to practice Catholicism in England and parts of the British Isles (c.1535–1790s). She will use the Shakespeare's World data in her research, in order to look for examples of Catholic women's writing.'

**Comment by simoneduca** [comment]
Who's included in the Alumni section?

**Comment by VVH** [comment]
Just Paul and Elizabeth with the new bios above. Thanks!
