### ISSUE TITLE
Quantify individual and collaborative page completions 

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#4]
I think it's important that we have a feature (just a banner within the project perhaps) where people can see:

1) how many words they've transcribed in total
2) how many pages they have completed
3) How many pages have been completed within a manuscript
4) How many pages completed across the project.

**Comment by rogerhutchings** [comment]
How about on the homepage, as with other projects?

**Comment by VVH** [comment]
That's what I was thinking, but then we might have to tweak for the individual's contribution

**Comment by simoneduca** [comment]
Is this a core feature, i.e. to be included in the beta, or a nice to have to include before the launch?

**Comment by VVH** [comment]
Non urgent, but this is one to come back to in March or April, if we have time. @simoneduca you can probably get this information from @ggdhines' aggregation code or possibly even just from the API on number of classifications. It's functionality that @simensta might want to include in future transcription projects.
