### ISSUE TITLE
Home page content

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#40]
Provide a short description of the project goals.

**Comment by VVH** [comment]
Hey @simoneduca I've gotten started on this and the FAQ page. https://docs.google.com/document/d/1x4gIWTljkhZzGFbAVjtxaV9i0MCgeMtqwpdl-pTImS8/edit

**Comment by DarrenMcRoy** [comment]
@VVH Would you like my help with this at all? I've done a lot of work with content for our sites, but I'll only help if I'm wanted. :-)
