### ISSUE TITLE
Decide on common abbreviations and TEI tags

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/shakespeares_world#55]
Currently, the following are the common abbreviations I've included in SW

`<anno></anno><esquire></esquire><examinant></examinant><honorable></honorable><inprimis></inprimis><item></item><lady></lady><mister></mister><mistress></mistress><our></our><paid></paid><sir></sir><which></which><with></with><the></the><that></that><your></your><-ment></-ment>`

and TEI tags

`<ins></ins><del></del><unclear></unclear><ex></ex>`

![screen shot 2015-08-25 at 15 55 35](https://cloud.githubusercontent.com/assets/8989606/9470009/cba0a91c-4b41-11e5-9b9b-ac8d69a4d833.png)

What is missing? And is the output in the transcription dialog correct?

**Comment by VVH** [comment]
We have received a file from @paul-dingman on 31 August with the relevant tag set. See email thread.

**Comment by simoneduca** [comment]
Here's the file from Paul for reference.
![screen shot 2015-09-03 at 15 46 34](https://cloud.githubusercontent.com/assets/8989606/9661533/05a2e856-5253-11e5-9401-8490038d96fb.png)

**Comment by simoneduca** [comment]
The current set of tags needs to be expanded to include those in the above document.
