### ISSUE TITLE
Pop up encouraging people to take a screen break

### ISSUE THREAD

**Issue by VVH** [zooniverse/shakespeares_world#63]
This is something we encourage when people use manuscripts in the flesh/paper. Could pop up every 45 minutes. A simple window with Shakespeare's head 'The Bard says: Take a break!' or Rest thine eyes.

**Comment by simoneduca** [comment]
I like it. What's the difference between this pop-up and intervention pop-ups? Also I think 45m is a long time. Is that the interval recommended for in the flesh transcriptions?
