### ISSUE TITLE
Unclear/unsure button remains toggled on when transcription box is closed

### ISSUE THREAD

**Issue by etobey** [zooniverse/shakespeares_world#75]
I was participating today in the Practical Paleography session at the Folger Library and was transcribing some of the documents in the beta version of Shakespeare's World. I noticed that if I clicked on the Unclear/unsure button when the transcription window was open, it seemed that the button remained toggled on, even after I closed the transcription window. I also noticed that when I went on to the next document, the first time I opened a new transcription window, the unclear/unsure XML tag had been automatically inserted into the window, and I had to manually delete it.

**Comment by simoneduca** [comment]
Superseded, closing.
