### ISSUE TITLE
Transcription and abbreviation boxes when tagging marginalia

### ISSUE THREAD

**Issue by etobey** [zooniverse/shakespeares_world#81]
I just noticed an issue with tagging marginalia. When I select and drag with the cursor to mark marginalia, the abbreviation menu comes up, but no transcription box. When I try to edit the marginalia item so I can enter the trasncription, the transcription box does open okay, but the abbreviation menu does not appear.

**Comment by VVH** [comment]
We've since changed the way marginalia is captured, so this is effectively a closed issue. Thanks Liz!
